### ISSUE TITLE
404 Not Found: /assets/templates/partials/topic/browsing-users.tpl

### ISSUE THREAD

**Issue by gtfr** [barisusakli/nodebb-plugin-browsing-users#1]
Hi,

I have installed your plugin, but do not see any change. Instead I found above error in the logs several thousand times!

Can you please check?

**Comment by barisusakli** [comment]
If you are not using the persona theme you need to add the require template into your theme. See this change https://github.com/NodeBB/nodebb-theme-persona/commit/387cd6fa72b12668a0c51fb09c1313d475e3d97e
